// Currency utility for the hotel management system
// This provides a centralized mapping of currency codes to symbols

export const currencySymbols = {
  'AED': 'د.إ',
  'AFN': '؋',
  'ALL': 'L',
  'AMD': '֏',
  'ANG': 'ƒ',
  'AOA': 'Kz',
  'ARS': '$',
  'AUD': 'A$',
  'AWG': 'ƒ',
  'AZN': '₼',
  'BAM': 'KM',
  'BBD': '$',
  'BDT': '৳',
  'BGN': 'лв',
  'BHD': '.د.ب',
  'BIF': 'Fr',
  'BMD': '$',
  'BND': '$',
  'BOB': 'Bs.',
  'BRL': 'R$',
  'BSD': '$',
  'BTN': 'Nu.',
  'BWP': 'P',
  'BYN': 'Br',
  'BZD': '$',
  'CAD': 'C$',
  'CDF': 'Fr',
  'CHF': 'Fr',
  'CLP': '$',
  'CNY': '¥',
  'COP': '$',
  'CRC': '₡',
  'CUP': '$',
  'CVE': '$',
  'CZK': 'Kč',
  'DJF': 'Fr',
  'DKK': 'kr',
  'DOP': '$',
  'DZD': 'د.ج',
  'EGP': '£',
  'ERN': 'Nfk',
  'ETB': 'Br',
  'EUR': '€',
  'FJD': '$',
  'FKP': '£',
  'FOK': 'kr',
  'GBP': '£',
  'GEL': '₾',
  'GGP': '£',
  'GHS': '₵',
  'GIP': '£',
  'GMD': 'D',
  'GNF': 'Fr',
  'GTQ': 'Q',
  'GYD': '$',
  'HKD': 'HK$',
  'HNL': 'L',
  'HRK': 'kn',
  'HTG': 'G',
  'HUF': 'Ft',
  'IDR': 'Rp',
  'ILS': '₪',
  'IMP': '£',
  'INR': '₹',
  'IQD': 'ع.د',
  'IRR': '﷼',
  'ISK': 'kr',
  'JEP': '£',
  'JMD': '$',
  'JOD': 'د.ا',
  'JPY': '¥',
  'KES': 'Sh',
  'KGS': 'с',
  'KHR': '៛',
  'KID': '$',
  'KMF': 'Fr',
  'KRW': '₩',
  'KWD': 'د.ك',
  'KYD': '$',
  'KZT': '₸',
  'LAK': '₭',
  'LBP': 'ل.ل',
  'LKR': 'Rs',
  'LRD': '$',
  'LSL': 'L',
  'LYD': 'ل.د',
  'MAD': 'د.م.',
  'MDL': 'L',
  'MGA': 'Ar',
  'MKD': 'ден',
  'MMK': 'K',
  'MNT': '₮',
  'MOP': 'P',
  'MRU': 'UM',
  'MUR': '₨',
  'MVR': '.ރ',
  'MWK': 'MK',
  'MXN': '$',
  'MYR': 'RM',
  'MZN': 'MT',
  'NAD': '$',
  'NGN': '₦',
  'NIO': 'C$',
  'NOK': 'kr',
  'NPR': '₨',
  'NZD': 'NZ$',
  'OMR': 'ر.ع.',
  'PAB': 'B/.',
  'PEN': 'S/.',
  'PGK': 'K',
  'PHP': '₱',
  'PKR': '₨',
  'PLN': 'zł',
  'PYG': '₲',
  'QAR': 'ر.ق',
  'RON': 'lei',
  'RSD': 'дин',
  'RUB': '₽',
  'RWF': 'Fr',
  'SAR': '﷼',
  'SBD': '$',
  'SCR': '₨',
  'SDG': '£',
  'SEK': 'kr',
  'SGD': 'S$',
  'SHP': '£',
  'SLE': 'Le',
  'SOS': 'Sh',
  'SPL': 'L',
  'SRD': '$',
  'STN': 'Db',
  'SYP': '£',
  'SZL': 'L',
  'THB': '฿',
  'TJS': 'ЅМ',
  'TMT': 'm',
  'TND': 'د.ت',
  'TOP': 'T$',
  'TRY': '₺',
  'TTD': '$',
  'TVD': '$',
  'TWD': 'NT$',
  'TZS': 'Sh',
  'UAH': '₴',
  'UGX': 'Sh',
  'USD': '$',
  'UYU': '$',
  'UZS': 'so\'m',
  'VES': 'Bs.',
  'VND': '₫',
  'VUV': 'Vt',
  'WST': 'T',
  'XAF': 'Fr',
  'XCD': '$',
  'XDR': 'SDR',
  'XOF': 'Fr',
  'XPF': 'Fr',
  'YER': '﷼',
  'ZAR': 'R',
  'ZMW': 'ZK',
  'ZWL': '$'
};

/**
 * Get the currency symbol for a given currency code
 * @param {string} currencyCode - The ISO currency code (e.g., 'USD', 'EUR', 'PKR')
 * @returns {string} The currency symbol (e.g., '$', '€', '₨')
 */
export const getCurrencySymbol = (currencyCode) => {
  return currencySymbols[currencyCode] || '$';
};

/**
 * Get the current currency symbol from localStorage
 * @returns {string} The currency symbol for the selected currency
 */
export const getCurrentCurrencySymbol = () => {
  if (typeof window === 'undefined') return '$';
  const currencyCode = localStorage.getItem('hotel_currency') || 'USD';
  return getCurrencySymbol(currencyCode);
};

/**
 * Format a number with the current currency symbol
 * @param {number} amount - The amount to format
 * @param {number} decimals - Number of decimal places (default: 2)
 * @returns {string} Formatted currency string
 */
export const formatCurrency = (amount, decimals = 2) => {
  const symbol = getCurrentCurrencySymbol();
  const formattedAmount = Number(amount).toFixed(decimals);
  return `${symbol}${formattedAmount}`;
};
